export const config = {
	URL_REDMINE: process.env.URL_REDMINE!,
	API_KEY_REDMINE: process.env.API_KEY_REDMINE!,
	USER_ID: process.env.USER_ID!,
	WEBHOOK_KEY_REDMINE: process.env.WEBHOOK_KEY_REDMINE!,
	WEBHOOK_TOKEN_REDMINE: process.env.WEBHOOK_TOKEN_REDMINE!,
	MIN_HOURS: 6,
	MIN_HOURS_FRIDAY: 4,
	API_KEY_WEATHER: process.env.API_KEY_WEATHER!,
	WEBHOOK_KEY_WEATHER: process.env.WEBHOOK_KEY_WEATHER!,
	WEBHOOK_TOKEN_WEATHER: process.env.WEBHOOK_TOKEN_WEATHER!,
};
